### ISSUE TITLE
Future plans for nanoplan

### ISSUE THREAD

**Issue by DJuego** [jsford/nanoplan#2]
The implementation of **D* Lite** will be an important milestone in the project. Already with that I would be quite satisfied. :-) 

However, have you thought about implementing some other state-of-the-art algorithm in the future in **nanoplan**? Is there already a to-do list? I love the minimalist philosophy that the project exudes!

DJuego

**Comment by jsford** [comment]
Hi DJuego! 

This is a side project for me right now, but I'd love to add more interesting algorithms. What kind of things would you like to see?

**Comment by DJuego** [comment]
Well. My main interests in approaching nanoplan are robotics and video games. I would need to work with your library to develop specific needs. 

>  nanoplan currently supports Dijkstra, A*, Lifelong Planning A*, and (Coming Soon!) D* Lite.

Already simply supporting Dijkstra, A*, Lifelong Planning A* and D* Lite I would be "satisfied" for the time being :yum:.  I understand that the D*Lite implementation is not yet finished... Right? ("Coming Soon!")

DJuego

**Comment by jsford** [comment]
That's right. Dijkstra, A*, and LPA* are working, but I wouldn't say they are exhaustively tested. D* Lite is mostly implemented, but seems to be buggy. I haven't had any time to work on it lately.

**Comment by DJuego** [comment]
Don't worry. Priorities are priorities, @jsford .

Thank you for your update! and, again, thank you for your contribution. If you only manage to support what you have it would already be a very valuable contribution. As I said it brings together a number of unique features that I have not seen in any other library on this topic. 

DJuego
